/**
 * Built-in model preset definitions for the Models Manager.
 * Each preset defines a model configuration that can be toggled on/off
 * in the managed models.ini.
 */

export interface ModelPreset {
	/** Unique identifier used as the ini section name */
	id: string;
	/** Human-readable display name */
	displayName: string;
	/** Minimum system RAM (MB) needed to run this model */
	minRamMB: number;
	/**
	 * Relative model quality (higher = better). Used by the onboarding
	 * recommendation to prefer quality over raw speed when picking a model
	 * that fits the machine.
	 */
	qualityRank: number;
	/** INI config lines (without section header or tracking comment) */
	iniLines: string[];
	/** Version number -- bumped when we change the preset config */
	version: number;
	/** If true, hidden from UI unless currently active in models.ini */
	deprecated?: true;
	/** ID of the replacement preset when deprecated (must not itself be deprecated) */
	successor?: string;
}

/**
 * All built-in model presets.
 * Order determines display order in the Models Manager UI.
 *
 * Ordered by minRamMB (ascending) — the "memory ladder" from
 * dev-docs/model-todo.md (≈4–128 GB including subagent rungs).
 *
 * Quality ranks reflect estimated output quality (model size × quant
 * fidelity), NOT memory order. Subagent (-p3) twins rank one above
 * their single-slot sibling so recommendation prefers 3-slot when it fits.
 */
export const MODEL_PRESETS: readonly ModelPreset[] = [
	// ── 128k single-slot (no p3 twins) ──────────────────────────────
	{
		id: 'qwen-3.5-2b:q4-128k',
		displayName: 'Qwen 3.5 2B (Q4, 128K)',
		minRamMB: 4096,
		qualityRank: 1,
		version: 1,
		iniLines: [
			'reasoning-preserve = true',
			'parallel = 1',
			'ctx-size = 131072',
			'threads-http = 16',
			'kv-unified = true',
			'metrics = true',
			'min-p = 0.0',
			'presence-penalty = 0.0',
			'temp = 0.6',
			'top-k = 20',
			'top-p = 0.95',
			'cache-ram = 1024',
			'swa-checkpoints = 32',
			'ctx-checkpoints = 32',
			'reasoning-budget-message = " ... Considering the limited time by the user, I have to give the solution based on the thinking directly now.\\n"',
			'flash-attn = on',
			'cache-type-k = bf16',
			'cache-type-v = bf16',
			"chat-template-kwargs = '{\"enable_thinking\":true}'",
			'hf = unsloth/Qwen3.5-2B-GGUF:UD-Q4_K_XL',
		],
	},
	{
		id: 'qwen-3.5-2b:q6-128k',
		displayName: 'Qwen 3.5 2B (Q6, 128K)',
		minRamMB: 5120,
		qualityRank: 2,
		version: 1,
		deprecated: true,
		successor: 'gemma-4-E2B-it:q4-128k',
		iniLines: [
			'reasoning-preserve = true',
			'parallel = 1',
			'ctx-size = 131072',
			'threads-http = 16',
			'kv-unified = true',
			'metrics = true',
			'min-p = 0.0',
			'presence-penalty = 0.0',
			'temp = 0.6',
			'top-k = 20',
			'top-p = 0.95',
			'cache-ram = 1024',
			'swa-checkpoints = 32',
			'ctx-checkpoints = 32',
			'reasoning-budget-message = " ... Considering the limited time by the user, I have to give the solution based on the thinking directly now.\\n"',
			'flash-attn = on',
			'cache-type-k = bf16',
			'cache-type-v = bf16',
			"chat-template-kwargs = '{\"enable_thinking\":true}'",
			'hf = unsloth/Qwen3.5-2B-GGUF:UD-Q6_K_XL',
		],
	},
	{
		id: 'gemma-4-E2B-it:q4-128k',
		displayName: 'Gemma 4 E2B (Q4, 128K)',
		minRamMB: 5120,
		qualityRank: 3,
		version: 1,
		iniLines: [
			'reasoning-preserve = true',
			'parallel = 1',
			'ctx-size = 131072',
			'threads-http = 16',
			'kv-unified = true',
			'metrics = true',
			'min-p = 0.0',
			'presence-penalty = 0.0',
			'spec-type = draft-mtp',
			'spec-draft-n-max = 2',
			'temp = 1.0',
			'top-k = 64',
			'top-p = 0.95',
			'cache-ram = 1024',
			'swa-checkpoints = 64',
			'ctx-checkpoints = 64',
			'reasoning-budget-message = "Proceed to final answer."',
			'flash-attn = on',
			'cache-type-k = f16',
			'cache-type-v = f16',
			'reasoning = on',
			'hf = unsloth/gemma-4-E2B-it-GGUF:UD-Q4_K_XL',
		],
	},
	{
		id: 'gemma-4-E4B-it:q4-128k',
		displayName: 'Gemma 4 E4B (Q4, 128K)',
		minRamMB: 8192,
		qualityRank: 4,
		version: 1,
		iniLines: [
			'reasoning-preserve = true',
			'parallel = 1',
			'ctx-size = 131072',
			'threads-http = 16',
			'kv-unified = true',
			'metrics = true',
			'min-p = 0.0',
			'presence-penalty = 0.0',
			'spec-type = draft-mtp',
			'spec-draft-n-max = 2',
			'temp = 1.0',
			'top-k = 64',
			'top-p = 0.95',
			'cache-ram = 2048',
			'swa-checkpoints = 64',
			'ctx-checkpoints = 64',
			'reasoning-budget-message = "Proceed to final answer."',
			'flash-attn = on',
			'cache-type-k = f16',
			'cache-type-v = f16',
			'reasoning = on',
			'hf = unsloth/gemma-4-E4B-it-GGUF:UD-Q4_K_XL',
		],
	},

	// ── 256k single-slot + subagent (-p3) twins ─────────────────────
	{
		id: 'qwen-3.5-4b:q4-256k',
		displayName: 'Qwen 3.5 4B (Q4, 256K)',
		minRamMB: 12288,
		qualityRank: 5,
		version: 1,
		iniLines: [
			'reasoning-preserve = true',
			'parallel = 1',
			'ctx-size = 262144',
			'threads-http = 16',
			'kv-unified = true',
			'metrics = true',
			'min-p = 0.0',
			'presence-penalty = 0.0',
			'temp = 0.6',
			'top-k = 20',
			'top-p = 0.95',
			'cache-ram = 2048',
			'swa-checkpoints = 64',
			'ctx-checkpoints = 64',
			'reasoning-budget-message = " ... Considering the limited time by the user, I have to give the solution based on the thinking directly now.\\n"',
			'flash-attn = on',
			'cache-type-k = bf16',
			'cache-type-v = bf16',
			"chat-template-kwargs = '{\"enable_thinking\":true}'",
			'hf = unsloth/Qwen3.5-4B-GGUF:UD-Q4_K_XL',
		],
	},
	{
		id: 'qwen-3.5-4b:q6-256k',
		displayName: 'Qwen 3.5 4B (Q6, 256K)',
		minRamMB: 14336,
		qualityRank: 6,
		version: 1,
		deprecated: true,
		successor: 'gemma-4-12B-it:q6-256k',
		iniLines: [
			'reasoning-preserve = true',
			'parallel = 1',
			'ctx-size = 262144',
			'threads-http = 16',
			'kv-unified = true',
			'metrics = true',
			'min-p = 0.0',
			'presence-penalty = 0.0',
			'temp = 0.6',
			'top-k = 20',
			'top-p = 0.95',
			'cache-ram = 2048',
			'swa-checkpoints = 64',
			'ctx-checkpoints = 64',
			'reasoning-budget-message = " ... Considering the limited time by the user, I have to give the solution based on the thinking directly now.\\n"',
			'flash-attn = on',
			'cache-type-k = bf16',
			'cache-type-v = bf16',
			"chat-template-kwargs = '{\"enable_thinking\":true}'",
			'hf = unsloth/Qwen3.5-4B-GGUF:UD-Q6_K_XL',
		],
	},
	{
		id: 'qwen-3.5-9b:q4-256k',
		displayName: 'Qwen 3.5 9B (Q4, 256K)',
		minRamMB: 15360,
		qualityRank: 8,
		version: 1,
		deprecated: true,
		successor: 'gemma-4-12B-it:q6-256k',
		iniLines: [
			'reasoning-preserve = true',
			'parallel = 1',
			'ctx-size = 262144',
			'threads-http = 16',
			'kv-unified = true',
			'metrics = true',
			'min-p = 0.0',
			'presence-penalty = 0.0',
			'temp = 0.6',
			'top-k = 20',
			'top-p = 0.95',
			'cache-ram = 4096',
			'swa-checkpoints = 64',
			'ctx-checkpoints = 64',
			'reasoning-budget-message = " ... Considering the limited time by the user, I have to give the solution based on the thinking directly now.\\n"',
			'flash-attn = on',
			'cache-type-k = bf16',
			'cache-type-v = bf16',
			"chat-template-kwargs = '{\"enable_thinking\":true}'",
			'hf = unsloth/Qwen3.5-9B-GGUF:UD-Q4_K_XL',
		],
	},
	{
		id: 'gemma-4-12B-it:q6-256k',
		displayName: 'Gemma 4 12B (Q6, 256K)',
		minRamMB: 16384,
		qualityRank: 17,
		version: 1,
		iniLines: [
			'reasoning-preserve = true',
			'parallel = 1',
			'ctx-size = 262144',
			'threads-http = 16',
			'kv-unified = true',
			'metrics = true',
			'min-p = 0.0',
			'presence-penalty = 0.0',
			'spec-type = draft-mtp',
			'spec-draft-n-max = 2',
			'temp = 1.0',
			'top-k = 64',
			'top-p = 0.95',
			'cache-ram = 4096',
			'swa-checkpoints = 128',
			'ctx-checkpoints = 128',
			'reasoning-budget-message = "Proceed to final answer."',
			'flash-attn = on',
			'cache-type-k = f16',
			'cache-type-v = f16',
			'reasoning = on',
			'hf = unsloth/gemma-4-12B-it-GGUF:UD-Q6_K_XL',
		],
	},
	{
		id: 'qwen-3.5-4b:bf16-256k',
		displayName: 'Qwen 3.5 4B (BF16, 256K)',
		minRamMB: 18432,
		qualityRank: 7,
		version: 1,
		deprecated: true,
		successor: 'gemma-4-12B-it:q6-256k',
		iniLines: [
			'reasoning-preserve = true',
			'parallel = 1',
			'ctx-size = 262144',
			'threads-http = 16',
			'kv-unified = true',
			'metrics = true',
			'min-p = 0.0',
			'presence-penalty = 0.0',
			'temp = 0.6',
			'top-k = 20',
			'top-p = 0.95',
			'cache-ram = 4096',
			'swa-checkpoints = 64',
			'ctx-checkpoints = 64',
			'reasoning-budget-message = " ... Considering the limited time by the user, I have to give the solution based on the thinking directly now.\\n"',
			'flash-attn = on',
			'cache-type-k = bf16',
			'cache-type-v = bf16',
			"chat-template-kwargs = '{\"enable_thinking\":true}'",
			'hf = unsloth/Qwen3.5-4B-GGUF:BF16',
		],
	},
	{
		id: 'gemma-4-12B-it:q8-256k',
		displayName: 'Gemma 4 12B (Q8, 256K)',
		minRamMB: 20480,
		qualityRank: 10,
		version: 1,
		deprecated: true,
		successor: 'gemma-4-26B-A4B-it:q4-256k',
		iniLines: [
			'reasoning-preserve = true',
			'parallel = 1',
			'ctx-size = 262144',
			'threads-http = 16',
			'kv-unified = true',
			'metrics = true',
			'min-p = 0.0',
			'presence-penalty = 0.0',
			'spec-type = draft-mtp',
			'spec-draft-n-max = 2',
			'temp = 1.0',
			'top-k = 64',
			'top-p = 0.95',
			'cache-ram = 4096',
			'swa-checkpoints = 128',
			'ctx-checkpoints = 128',
			'reasoning-budget-message = "Proceed to final answer."',
			'flash-attn = on',
			'cache-type-k = f16',
			'cache-type-v = f16',
			'reasoning = on',
			'hf = unsloth/gemma-4-12B-it-GGUF:UD-Q8_K_XL',
		],
	},
	{
		id: 'gemma-4-26B-A4B-it:q4-256k',
		displayName: 'Gemma 4 26B-A4B (Q4, 256K)',
		minRamMB: 24576,
		qualityRank: 19,
		version: 1,
		iniLines: [
			'reasoning-preserve = true',
			'parallel = 1',
			'ctx-size = 262144',
			'threads-http = 16',
			'kv-unified = true',
			'metrics = true',
			'min-p = 0.0',
			'presence-penalty = 0.0',
			'spec-type = draft-mtp',
			'spec-draft-n-max = 2',
			'temp = 1.0',
			'top-k = 64',
			'top-p = 0.95',
			'cache-ram = 4096',
			'swa-checkpoints = 128',
			'ctx-checkpoints = 128',
			'reasoning-budget-message = "Proceed to final answer."',
			'flash-attn = on',
			'cache-type-k = f16',
			'cache-type-v = f16',
			'reasoning = on',
			'hf = unsloth/gemma-4-26B-A4B-it-GGUF:UD-Q4_K_XL',
		],
	},
	{
		id: 'gemma-4-12B-it:q6-256k-p3',
		displayName: 'Gemma 4 12B (Q6, 256K\u00d73)',
		minRamMB: 25600,
		qualityRank: 18,
		version: 1,
		iniLines: [
			'reasoning-preserve = true',
			'parallel = 3',
			'ctx-size = 786432',
			'threads-http = 16',
			'kv-unified = true',
			'metrics = true',
			'min-p = 0.0',
			'presence-penalty = 0.0',
			'spec-type = draft-mtp',
			'spec-draft-n-max = 2',
			'temp = 1.0',
			'top-k = 64',
			'top-p = 0.95',
			'cache-ram = 12288',
			'swa-checkpoints = 128',
			'ctx-checkpoints = 128',
			'reasoning-budget-message = "Proceed to final answer."',
			'flash-attn = on',
			'cache-type-k = f16',
			'cache-type-v = f16',
			'reasoning = on',
			'hf = unsloth/gemma-4-12B-it-GGUF:UD-Q6_K_XL',
		],
	},
	{
		id: 'qwen-3.6-35b:q4-256k',
		displayName: 'Qwen 3.6 35B (Q4, 256K)',
		minRamMB: 28672,
		qualityRank: 12,
		version: 1,
		deprecated: true,
		successor: 'qwen-3.6-35b:q6-256k',
		iniLines: [
			'image-min-tokens = 1024',
			'reasoning-preserve = true',
			'parallel = 1',
			'ctx-size = 262144',
			'threads-http = 16',
			'kv-unified = true',
			'metrics = true',
			'min-p = 0.0',
			'presence-penalty = 0.0',
			'spec-type = draft-mtp',
			'spec-draft-n-max = 2',
			'temp = 0.6',
			'top-k = 20',
			'top-p = 0.95',
			'cache-ram = 8192',
			'swa-checkpoints = 128',
			'ctx-checkpoints = 128',
			'reasoning-budget-message = " ... Considering the limited time by the user, I have to give the solution based on the thinking directly now.\\n"',
			'flash-attn = on',
			'cache-type-k = bf16',
			'cache-type-v = bf16',
			'hf = unsloth/Qwen3.6-35B-A3B-MTP-GGUF:UD-Q4_K_XL',
		],
	},
	{
		id: 'qwen-3.5-4b:q4-256k-p3',
		displayName: 'Qwen 3.5 4B (Q4, 256K\u00d73)',
		minRamMB: 29696,
		qualityRank: 16,
		version: 1,
		iniLines: [
			'reasoning-preserve = true',
			'parallel = 3',
			'ctx-size = 786432',
			'threads-http = 16',
			'kv-unified = true',
			'metrics = true',
			'min-p = 0.0',
			'presence-penalty = 0.0',
			'temp = 0.6',
			'top-k = 20',
			'top-p = 0.95',
			'cache-ram = 6144',
			'swa-checkpoints = 64',
			'ctx-checkpoints = 64',
			'reasoning-budget-message = " ... Considering the limited time by the user, I have to give the solution based on the thinking directly now.\\n"',
			'flash-attn = on',
			'cache-type-k = bf16',
			'cache-type-v = bf16',
			"chat-template-kwargs = '{\"enable_thinking\":true}'",
			'hf = unsloth/Qwen3.5-4B-GGUF:UD-Q4_K_XL',
		],
	},
	{
		id: 'gemma-4-26B-A4B-it:q6-256k',
		displayName: 'Gemma 4 26B-A4B (Q6, 256K)',
		minRamMB: 30720,
		qualityRank: 13,
		version: 1,
		deprecated: true,
		successor: 'qwen-3.6-35b:q6-256k',
		iniLines: [
			'reasoning-preserve = true',
			'parallel = 1',
			'ctx-size = 262144',
			'threads-http = 16',
			'kv-unified = true',
			'metrics = true',
			'min-p = 0.0',
			'presence-penalty = 0.0',
			'spec-type = draft-mtp',
			'spec-draft-n-max = 2',
			'temp = 1.0',
			'top-k = 64',
			'top-p = 0.95',
			'cache-ram = 4096',
			'swa-checkpoints = 128',
			'ctx-checkpoints = 128',
			'reasoning-budget-message = "Proceed to final answer."',
			'flash-attn = on',
			'cache-type-k = f16',
			'cache-type-v = f16',
			'reasoning = on',
			'hf = unsloth/gemma-4-26B-A4B-it-GGUF:UD-Q6_K_XL',
		],
	},
	{
		id: 'gemma-4-26B-A4B-it:q4-256k-p3',
		displayName: 'Gemma 4 26B-A4B (Q4, 256K\u00d73)',
		minRamMB: 34816,
		qualityRank: 20,
		version: 1,
		iniLines: [
			'reasoning-preserve = true',
			'parallel = 3',
			'ctx-size = 786432',
			'threads-http = 16',
			'kv-unified = true',
			'metrics = true',
			'min-p = 0.0',
			'presence-penalty = 0.0',
			'spec-type = draft-mtp',
			'spec-draft-n-max = 2',
			'temp = 1.0',
			'top-k = 64',
			'top-p = 0.95',
			'cache-ram = 12288',
			'swa-checkpoints = 128',
			'ctx-checkpoints = 128',
			'reasoning-budget-message = "Proceed to final answer."',
			'flash-attn = on',
			'cache-type-k = f16',
			'cache-type-v = f16',
			'reasoning = on',
			'hf = unsloth/gemma-4-26B-A4B-it-GGUF:UD-Q4_K_XL',
		],
	},
	{
		id: 'qwen-3.6-27b:q4-256k',
		displayName: 'Qwen 3.6 27B (Q4, 256K)',
		minRamMB: 35840,
		qualityRank: 14,
		version: 1,
		deprecated: true,
		successor: 'qwen-3.6-27b:q6-256k',
		iniLines: [
			'image-min-tokens = 1024',
			'reasoning-preserve = true',
			'parallel = 1',
			'ctx-size = 262144',
			'threads-http = 16',
			'kv-unified = true',
			'metrics = true',
			'min-p = 0.0',
			'presence-penalty = 0.0',
			'spec-type = draft-mtp',
			'spec-draft-n-max = 2',
			'temp = 0.6',
			'top-k = 20',
			'top-p = 0.95',
			'cache-ram = 8192',
			'swa-checkpoints = 128',
			'ctx-checkpoints = 128',
			'reasoning-budget-message = " ... Considering the limited time by the user, I have to give the solution based on the thinking directly now.\\n"',
			'flash-attn = on',
			'cache-type-k = bf16',
			'cache-type-v = bf16',
			'hf = unsloth/Qwen3.6-27B-MTP-GGUF:UD-Q4_K_XL',
		],
	},
	{
		id: 'qwen-3.6-35b:q6-256k',
		displayName: 'Qwen 3.6 35B (Q6, 256K)',
		minRamMB: 36864,
		qualityRank: 21,
		version: 1,
		iniLines: [
			'image-min-tokens = 1024',
			'reasoning-preserve = true',
			'parallel = 1',
			'ctx-size = 262144',
			'threads-http = 16',
			'kv-unified = true',
			'metrics = true',
			'min-p = 0.0',
			'presence-penalty = 0.0',
			'spec-type = draft-mtp',
			'spec-draft-n-max = 2',
			'temp = 0.6',
			'top-k = 20',
			'top-p = 0.95',
			'cache-ram = 8192',
			'swa-checkpoints = 128',
			'ctx-checkpoints = 128',
			'reasoning-budget-message = " ... Considering the limited time by the user, I have to give the solution based on the thinking directly now.\\n"',
			'flash-attn = on',
			'cache-type-k = bf16',
			'cache-type-v = bf16',
			'hf = unsloth/Qwen3.6-35B-A3B-MTP-GGUF:UD-Q6_K_XL',
		],
	},

	// ── High-RAM single-slot + subagent twins ───────────────────────
	{
		id: 'qwen-3.6-35b:q8-256k',
		displayName: 'Qwen 3.6 35B (Q8, 256K)',
		minRamMB: 45056,
		qualityRank: 23,
		version: 1,
		iniLines: [
			'image-min-tokens = 1024',
			'reasoning-preserve = true',
			'parallel = 1',
			'ctx-size = 262144',
			'threads-http = 16',
			'kv-unified = true',
			'metrics = true',
			'min-p = 0.0',
			'presence-penalty = 0.0',
			'spec-type = draft-mtp',
			'spec-draft-n-max = 2',
			'temp = 0.6',
			'top-k = 20',
			'top-p = 0.95',
			'cache-ram = 8192',
			'swa-checkpoints = 128',
			'ctx-checkpoints = 128',
			'reasoning-budget-message = " ... Considering the limited time by the user, I have to give the solution based on the thinking directly now.\\n"',
			'flash-attn = on',
			'cache-type-k = bf16',
			'cache-type-v = bf16',
			'hf = unsloth/Qwen3.6-35B-A3B-MTP-GGUF:UD-Q8_K_XL',
		],
	},
	{
		id: 'qwen-3.6-35b:q6-256k-p3',
		displayName: 'Qwen 3.6 35B (Q6, 256K\u00d73)',
		minRamMB: 47104,
		qualityRank: 22,
		version: 1,
		iniLines: [
			'image-min-tokens = 1024',
			'reasoning-preserve = true',
			'parallel = 3',
			'ctx-size = 786432',
			'threads-http = 16',
			'kv-unified = true',
			'metrics = true',
			'min-p = 0.0',
			'presence-penalty = 0.0',
			'spec-type = draft-mtp',
			'spec-draft-n-max = 2',
			'temp = 0.6',
			'top-k = 20',
			'top-p = 0.95',
			'cache-ram = 24576',
			'swa-checkpoints = 128',
			'ctx-checkpoints = 128',
			'reasoning-budget-message = " ... Considering the limited time by the user, I have to give the solution based on the thinking directly now.\\n"',
			'flash-attn = on',
			'cache-type-k = bf16',
			'cache-type-v = bf16',
			'hf = unsloth/Qwen3.6-35B-A3B-MTP-GGUF:UD-Q6_K_XL',
		],
	},
	{
		id: 'qwen-3.6-27b:q6-256k',
		displayName: 'Qwen 3.6 27B (Q6, 256K)',
		minRamMB: 49152,
		qualityRank: 25,
		version: 1,
		iniLines: [
			'image-min-tokens = 1024',
			'reasoning-preserve = true',
			'parallel = 1',
			'ctx-size = 262144',
			'threads-http = 16',
			'kv-unified = true',
			'metrics = true',
			'min-p = 0.0',
			'presence-penalty = 0.0',
			'spec-type = draft-mtp',
			'spec-draft-n-max = 2',
			'temp = 0.6',
			'top-k = 20',
			'top-p = 0.95',
			'cache-ram = 8192',
			'swa-checkpoints = 128',
			'ctx-checkpoints = 128',
			'reasoning-budget-message = " ... Considering the limited time by the user, I have to give the solution based on the thinking directly now.\\n"',
			'flash-attn = on',
			'cache-type-k = bf16',
			'cache-type-v = bf16',
			'hf = unsloth/Qwen3.6-27B-MTP-GGUF:UD-Q6_K_XL',
		],
	},
	{
		id: 'qwen-3.6-35b:q8-256k-p3',
		displayName: 'Qwen 3.6 35B (Q8, 256K\u00d73)',
		minRamMB: 55296,
		qualityRank: 24,
		version: 1,
		iniLines: [
			'image-min-tokens = 1024',
			'reasoning-preserve = true',
			'parallel = 3',
			'ctx-size = 786432',
			'threads-http = 16',
			'kv-unified = true',
			'metrics = true',
			'min-p = 0.0',
			'presence-penalty = 0.0',
			'spec-type = draft-mtp',
			'spec-draft-n-max = 2',
			'temp = 0.6',
			'top-k = 20',
			'top-p = 0.95',
			'cache-ram = 24576',
			'swa-checkpoints = 128',
			'ctx-checkpoints = 128',
			'reasoning-budget-message = " ... Considering the limited time by the user, I have to give the solution based on the thinking directly now.\\n"',
			'flash-attn = on',
			'cache-type-k = bf16',
			'cache-type-v = bf16',
			'hf = unsloth/Qwen3.6-35B-A3B-MTP-GGUF:UD-Q8_K_XL',
		],
	},
	{
		id: 'gemma-4-26B-A4B-it:bf16-256k',
		displayName: 'Gemma 4 26B-A4B (BF16, 256K)',
		minRamMB: 56064,
		qualityRank: 27,
		version: 1,
		iniLines: [
			'reasoning-preserve = true',
			'parallel = 1',
			'ctx-size = 262144',
			'threads-http = 16',
			'kv-unified = true',
			'metrics = true',
			'min-p = 0.0',
			'presence-penalty = 0.0',
			'spec-type = draft-mtp',
			'spec-draft-n-max = 2',
			'temp = 1.0',
			'top-k = 64',
			'top-p = 0.95',
			'cache-ram = 4096',
			'swa-checkpoints = 128',
			'ctx-checkpoints = 128',
			'reasoning-budget-message = "Proceed to final answer."',
			'flash-attn = on',
			'cache-type-k = f16',
			'cache-type-v = f16',
			'reasoning = on',
			'hf = unsloth/gemma-4-26B-A4B-it-GGUF:BF16',
		],
	},
	{
		id: 'qwen-3.6-27b:bf16-256k',
		displayName: 'Qwen 3.6 27B (BF16, 256K)',
		minRamMB: 65536,
		qualityRank: 29,
		version: 1,
		iniLines: [
			'image-min-tokens = 1024',
			'reasoning-preserve = true',
			'parallel = 1',
			'ctx-size = 262144',
			'threads-http = 16',
			'kv-unified = true',
			'metrics = true',
			'min-p = 0.0',
			'presence-penalty = 0.0',
			'spec-type = draft-mtp',
			'spec-draft-n-max = 2',
			'temp = 0.6',
			'top-k = 20',
			'top-p = 0.95',
			'cache-ram = 8192',
			'swa-checkpoints = 128',
			'ctx-checkpoints = 128',
			'reasoning-budget-message = " ... Considering the limited time by the user, I have to give the solution based on the thinking directly now.\\n"',
			'flash-attn = on',
			'cache-type-k = bf16',
			'cache-type-v = bf16',
			'hf = unsloth/Qwen3.6-27B-MTP-GGUF:BF16',
		],
	},
	{
		id: 'gemma-4-26B-A4B-it:bf16-256k-p3',
		displayName: 'Gemma 4 26B-A4B (BF16, 256K\u00d73)',
		minRamMB: 67584,
		qualityRank: 28,
		version: 1,
		iniLines: [
			'reasoning-preserve = true',
			'parallel = 3',
			'ctx-size = 786432',
			'threads-http = 16',
			'kv-unified = true',
			'metrics = true',
			'min-p = 0.0',
			'presence-penalty = 0.0',
			'spec-type = draft-mtp',
			'spec-draft-n-max = 2',
			'temp = 1.0',
			'top-k = 64',
			'top-p = 0.95',
			'cache-ram = 12288',
			'swa-checkpoints = 128',
			'ctx-checkpoints = 128',
			'reasoning-budget-message = "Proceed to final answer."',
			'flash-attn = on',
			'cache-type-k = f16',
			'cache-type-v = f16',
			'reasoning = on',
			'hf = unsloth/gemma-4-26B-A4B-it-GGUF:BF16',
		],
	},
	{
		id: 'qwen-3.6-27b:q6-256k-p3',
		displayName: 'Qwen 3.6 27B (Q6, 256K\u00d73)',
		minRamMB: 81920,
		qualityRank: 26,
		version: 1,
		iniLines: [
			'image-min-tokens = 1024',
			'reasoning-preserve = true',
			'parallel = 3',
			'ctx-size = 786432',
			'threads-http = 16',
			'kv-unified = true',
			'metrics = true',
			'min-p = 0.0',
			'presence-penalty = 0.0',
			'spec-type = draft-mtp',
			'spec-draft-n-max = 2',
			'temp = 0.6',
			'top-k = 20',
			'top-p = 0.95',
			'cache-ram = 24576',
			'swa-checkpoints = 128',
			'ctx-checkpoints = 128',
			'reasoning-budget-message = " ... Considering the limited time by the user, I have to give the solution based on the thinking directly now.\\n"',
			'flash-attn = on',
			'cache-type-k = bf16',
			'cache-type-v = bf16',
			'hf = unsloth/Qwen3.6-27B-MTP-GGUF:UD-Q6_K_XL',
		],
	},
	{
		id: 'qwen-3.6-27b:bf16-256k-p3',
		displayName: 'Qwen 3.6 27B (BF16, 256K\u00d73)',
		minRamMB: 98304,
		qualityRank: 30,
		version: 1,
		iniLines: [
			'image-min-tokens = 1024',
			'reasoning-preserve = true',
			'parallel = 3',
			'ctx-size = 786432',
			'threads-http = 16',
			'kv-unified = true',
			'metrics = true',
			'min-p = 0.0',
			'presence-penalty = 0.0',
			'spec-type = draft-mtp',
			'spec-draft-n-max = 2',
			'temp = 0.6',
			'top-k = 20',
			'top-p = 0.95',
			'cache-ram = 24576',
			'swa-checkpoints = 128',
			'ctx-checkpoints = 128',
			'reasoning-budget-message = " ... Considering the limited time by the user, I have to give the solution based on the thinking directly now.\\n"',
			'flash-attn = on',
			'cache-type-k = bf16',
			'cache-type-v = bf16',
			'hf = unsloth/Qwen3.6-27B-MTP-GGUF:BF16',
		],
	},
];

/**
 * Get a preset by ID.
 */
export function getPresetById(id: string): ModelPreset | undefined {
	return MODEL_PRESETS.find(p => p.id === id);
}

/**
 * Validate that no deprecated preset's successor is also deprecated.
 * Used in tests as a compile-time assertion.
 */
export function validatePresetChains(): string[] {
	const errors: string[] = [];
	for (const preset of MODEL_PRESETS) {
		if (preset.deprecated && preset.successor) {
			const successor = getPresetById(preset.successor);
			if (!successor) {
				errors.push(`Preset "${preset.id}" has successor "${preset.successor}" which does not exist.`);
			} else if (successor.deprecated) {
				errors.push(`Preset "${preset.id}" has successor "${preset.successor}" which is also deprecated (deprecation chain).`);
			}
		}
	}
	return errors;
}
